// ---------- Секретные данные: ученик НЕ видит их содержимое ----------
// Все задачи получают эти переменные, но в UI отображается только имя + тип.
const SECRET_DATA = {
  // ================== ТЕМА 1. Поиск по индексу ==================
  fruits:          ["яблоко", "банан", "вишня", "груша", "слива", "персик"],
  cities:          ["Москва", "Париж", "Токио", "Каир", "Берлин", "Мадрид", "Рим"],
  colors:          ["красный", "зелёный", "синий", "жёлтый", "фиолетовый"],
  planets:         ["Меркурий", "Венера", "Земля", "Марс", "Юпитер", "Сатурн"],
  digits:          [10, 20, 30, 40, 50, 60, 70, 80],
  weekdays:        ["понедельник", "вторник", "среда", "четверг", "пятница", "суббота", "воскресенье"],
  months:          ["январь", "февраль", "март", "апрель", "май", "июнь",
                    "июль", "август", "сентябрь", "октябрь", "ноябрь", "декабрь"],
  numbers_seq:     [5, 10, 15, 20, 25, 30, 35, 40, 45, 50],
  countries_idx:   ["Россия", "Китай", "Индия", "США", "Бразилия", "Канада"],
  pets:            ["кошка", "собака", "попугай", "хомяк", "рыбка", "черепаха"],

  // ================== ТЕМА 2. Поиск по значению ==================
  students:        ["Аня", "Петя", "Миша", "Катя", "Олег", "Даша", "Игорь"],
  animals:         ["кот", "собака", "лиса", "волк", "медведь", "заяц", "ёж"],
  countries:       ["Россия", "Франция", "Япония", "Египет", "Германия", "Италия"],
  languages:       ["Python", "Java", "C++", "JavaScript", "Go", "Rust", "Kotlin"],
  numbers_search:  [7, 14, 21, 28, 35, 42, 49, 56, 63],
  songs:           ["Калинка", "Катюша", "Подмосковные вечера", "Очи чёрные"],
  grades:          [5, 4, 3, 5, 4, 2, 5, 4, 3],
  books:           ["Война и мир", "Преступление и наказание", "Мастер и Маргарита", "Евгений Онегин"],
  sports:          ["футбол", "баскетбол", "теннис", "плавание", "бокс", "шахматы"],
  transport:       ["автобус", "трамвай", "метро", "такси", "велосипед"],

  // ================== ТЕМА 3. Добавление элементов ==================
  base_fruits:     ["яблоко", "банан", "вишня"],
  base_numbers:    [1, 2, 3],
  base_cities:     ["Москва", "Париж"],
  base_colors:     ["красный", "зелёный"],
  base_names:      ["Аня", "Петя"],
  base_grades:     [5, 4, 3],
  base_pets:       ["кошка", "собака"],
  base_days:       ["понедельник", "вторник"],
  base_sports:     ["футбол", "теннис"],
  base_books:      ["Война и мир"],

  // ================== ТЕМА 4. Удаление элементов ==================
  del_fruits:      ["яблоко", "банан", "вишня", "груша", "слива"],
  del_numbers:     [10, 20, 30, 40, 50],
  del_cities:      ["Москва", "Париж", "Токио", "Каир"],
  del_colors:      ["красный", "зелёный", "синий", "жёлтый"],
  del_names:       ["Аня", "Петя", "Миша", "Катя", "Олег"],
  del_grades:      [5, 4, 2, 3, 5, 4],
  del_pets:        ["кошка", "собака", "хомяк", "рыбка"],
  del_days:        ["понедельник", "вторник", "среда", "четверг", "пятница"],
  del_sports:      ["футбол", "теннис", "бокс", "шахматы"],
  del_books:       ["Война и мир", "Мастер и Маргарита", "Евгений Онегин", "Отцы и дети"],
};

// ---------- Конфиг задач ----------
const TASKS = [
  // ============================================================
  // ТЕМА 1. Поиск по индексу в списке (10 задач)
  // ============================================================
  {
    id: "idx-1",
    title: "1.1. Третий фрукт",
    desc: "Дан список fruits. Получите элемент с индексом 2 и сохраните его в переменную result.",
    vars: [{ name: "fruits", type: "list[str]" }],
    setup: `fruits = ${JSON.stringify(SECRET_DATA.fruits)}`,
    starter: ``,
    hint: "Индексация в Python начинается с 0. Третий элемент — fruits[2].",
    expected: { result: "вишня" },
  },
  {
    id: "idx-2",
    title: "1.2. Первая столица",
    desc: "Дан список cities. Получите первый элемент списка и сохраните его в result.",
    vars: [{ name: "cities", type: "list[str]" }],
    setup: `cities = ${JSON.stringify(SECRET_DATA.cities)}`,
    starter: ``,
    hint: "Первый элемент — cities[0].",
    expected: { result: "Москва" },
  },
  {
    id: "idx-3",
    title: "1.3. Последний цвет радуги",
    desc: "Дан список colors. Получите последний элемент списка и сохраните его в result.",
    vars: [{ name: "colors", type: "list[str]" }],
    setup: `colors = ${JSON.stringify(SECRET_DATA.colors)}`,
    starter: ``,
    hint: "Последний элемент можно получить через colors[-1] или colors[len(colors) - 1].",
    expected: { result: "фиолетовый" },
  },
  {
    id: "idx-4",
    title: "1.4. Предпоследняя планета",
    desc: "Дан список planets. Получите предпоследний элемент и сохраните его в result.",
    vars: [{ name: "planets", type: "list[str]" }],
    setup: `planets = ${JSON.stringify(SECRET_DATA.planets)}`,
    starter: ``,
    hint: "Предпоследний элемент — planets[-2].",
    expected: { result: "Сатурн" },
  },
  {
    id: "idx-5",
    title: "1.5. Пятое число",
    desc: "Дан список digits. Получите элемент с индексом 4 и сохраните его в result.",
    vars: [{ name: "digits", type: "list[int]" }],
    setup: `digits = ${JSON.stringify(SECRET_DATA.digits)}`,
    starter: ``,
    hint: "Индекс 4 — это пятый по счёту элемент.",
    expected: { result: 50 },
  },
  {
    id: "idx-6",
    title: "1.6. Среда",
    desc: "Дан список weekdays. Получите элемент с индексом 2 (это третий день недели) и сохраните его в result.",
    vars: [{ name: "weekdays", type: "list[str]" }],
    setup: `weekdays = ${JSON.stringify(SECRET_DATA.weekdays)}`,
    starter: ``,
    hint: "weekdays[2].",
    expected: { result: "среда" },
  },
  {
    id: "idx-7",
    title: "1.7. Летний месяц",
    desc: "Дан список months. Получите элемент с индексом 5 и сохраните его в result. (Подсказка: индекс 5 — это июнь.)",
    vars: [{ name: "months", type: "list[str]" }],
    setup: `months = ${JSON.stringify(SECRET_DATA.months)}`,
    starter: ``,
    hint: "months[5].",
    expected: { result: "июнь" },
  },
  {
    id: "idx-8",
    title: "1.8. Диапазон индексов",
    desc: "Дан список numbers_seq. Получите срез — элементы с индексами от 2 до 5 (не включая 5) — и сохраните список в result.",
    vars: [{ name: "numbers_seq", type: "list[int]" }],
    setup: `numbers_seq = ${JSON.stringify(SECRET_DATA.numbers_seq)}`,
    starter: ``,
    hint: "Срез списка: numbers_seq[2:5] вернёт элементы с индексами 2, 3, 4.",
    expected: { result: [15, 20, 25] },
  },
  {
    id: "idx-9",
    title: "1.9. Через один",
    desc: "Дан список numbers_seq. Получите срез из каждого второго элемента, начиная с индекса 0, и сохраните его в result.",
    vars: [{ name: "numbers_seq", type: "list[int]" }],
    setup: `numbers_seq = ${JSON.stringify(SECRET_DATA.numbers_seq)}`,
    starter: ``,
    hint: "Срез с шагом: numbers_seq[::2] берёт элементы 0, 2, 4, ...",
    expected: { result: [5, 15, 25, 35, 45] },
  },
  {
    id: "idx-10",
    title: "1.10. Длина списка",
    desc: "Дан список countries_idx. Получите количество элементов в списке и сохраните его в result.",
    vars: [{ name: "countries_idx", type: "list[str]" }],
    setup: `countries_idx = ${JSON.stringify(SECRET_DATA.countries_idx)}`,
    starter: ``,
    hint: "Функция len() возвращает длину списка.",
    expected: { result: 6 },
  },

  // ============================================================
  // ТЕМА 2. Поиск по значению (10 задач)
  // ============================================================
  {
    id: "find-1",
    title: "2.1. Индекс Миши",
    desc: "Дан список students. Найдите индекс (позицию) элемента 'Миша' и сохраните его в result.",
    vars: [{ name: "students", type: "list[str]" }],
    setup: `students = ${JSON.stringify(SECRET_DATA.students)}`,
    starter: ``,
    hint: "Используйте метод списка .index() — например, students.index(\"Миша\").",
    expected: { result: 2 },
  },
  {
    id: "find-2",
    title: "2.2. Позиция волка",
    desc: "Дан список animals. Найдите индекс элемента 'волк' и сохраните его в result.",
    vars: [{ name: "animals", type: "list[str]" }],
    setup: `animals = ${JSON.stringify(SECRET_DATA.animals)}`,
    starter: ``,
    hint: "animals.index(\"волк\").",
    expected: { result: 3 },
  },
  {
    id: "find-3",
    title: "2.3. Где Япония?",
    desc: "Дан список countries. Найдите индекс элемента 'Япония' и сохраните его в result.",
    vars: [{ name: "countries", type: "list[str]" }],
    setup: `countries = ${JSON.stringify(SECRET_DATA.countries)}`,
    starter: ``,
    hint: "countries.index(\"Япония\").",
    expected: { result: 2 },
  },
  {
    id: "find-4",
    title: "2.4. Есть ли Python?",
    desc: "Дан список languages. Проверьте, есть ли в нём 'Python'. Если есть — сохраните в result слово 'да', иначе — 'нет'.",
    vars: [{ name: "languages", type: "list[str]" }],
    setup: `languages = ${JSON.stringify(SECRET_DATA.languages)}`,
    starter: ``,
    hint: "Проверка через оператор in: \"Python\" in languages. Затем if/else.",
    expected: { result: "да" },
  },
  {
    id: "find-5",
    title: "2.5. Индекс числа 42",
    desc: "Дан список numbers_search. Найдите индекс числа 42 и сохраните его в result.",
    vars: [{ name: "numbers_search", type: "list[int]" }],
    setup: `numbers_search = ${JSON.stringify(SECRET_DATA.numbers_search)}`,
    starter: ``,
    hint: "numbers_search.index(42).",
    expected: { result: 5 },
  },
  {
    id: "find-6",
    title: "2.6. Позиция Катюши",
    desc: "Дан список songs. Найдите индекс песни 'Катюша' и сохраните его в result.",
    vars: [{ name: "songs", type: "list[str]" }],
    setup: `songs = ${JSON.stringify(SECRET_DATA.songs)}`,
    starter: ``,
    hint: "songs.index(\"Катюша\").",
    expected: { result: 1 },
  },
  {
    id: "find-7",
    title: "2.7. Есть ли двойка?",
    desc: "Дан список grades. Проверьте, есть ли в нём оценка 2. Если есть — сохраните в result 'да', иначе — 'нет'.",
    vars: [{ name: "grades", type: "list[int]" }],
    setup: `grades = ${JSON.stringify(SECRET_DATA.grades)}`,
    starter: ``,
    hint: "2 in grades возвращает True или False. Используйте if/else.",
    expected: { result: "да" },
  },
  {
    id: "find-8",
    title: "2.8. Сколько раз встречается пятёрка?",
    desc: "Дан список grades. Посчитайте, сколько раз встречается оценка 5, и сохраните количество в result.",
    vars: [{ name: "grades", type: "list[int]" }],
    setup: `grades = ${JSON.stringify(SECRET_DATA.grades)}`,
    starter: ``,
    hint: "Метод .count(значение) возвращает число вхождений.",
    expected: { result: 3 },
  },
  {
    id: "find-9",
    title: "2.9. Есть ли шахматы?",
    desc: "Дан список sports. Проверьте, есть ли в нём 'шахматы'. Если есть — сохраните в result 'да', иначе — 'нет'.",
    vars: [{ name: "sports", type: "list[str]" }],
    setup: `sports = ${JSON.stringify(SECRET_DATA.sports)}`,
    starter: ``,
    hint: "\"шахматы\" in sports.",
    expected: { result: "да" },
  },
  {
    id: "find-10",
    title: "2.10. Индекс велосипеда",
    desc: "Дан список transport. Найдите индекс элемента 'велосипед' и сохраните его в result.",
    vars: [{ name: "transport", type: "list[str]" }],
    setup: `transport = ${JSON.stringify(SECRET_DATA.transport)}`,
    starter: ``,
    hint: "transport.index(\"велосипед\").",
    expected: { result: 4 },
  },

  // ============================================================
  // ТЕМА 3. Добавление элементов в список (10 задач)
  // ============================================================
  {
    id: "add-1",
    title: "3.1. Добавить апельсин",
    desc: "Дан список base_fruits. Добавьте в конец строку 'апельсин'. Сохраните получившийся список в result.",
    vars: [{ name: "base_fruits", type: "list[str]" }],
    setup: `base_fruits = ${JSON.stringify(SECRET_DATA.base_fruits)}`,
    starter: ``,
    hint: "Метод .append() добавляет элемент в конец.",
    expected: { result: ["яблоко", "банан", "вишня", "апельсин"] },
  },
  {
    id: "add-2",
    title: "3.2. Добавить четвёрку",
    desc: "Дан список base_numbers. Добавьте в конец число 4. Сохраните результат в result.",
    vars: [{ name: "base_numbers", type: "list[int]" }],
    setup: `base_numbers = ${JSON.stringify(SECRET_DATA.base_numbers)}`,
    starter: ``,
    hint: "base_numbers.append(4); result = base_numbers.",
    expected: { result: [1, 2, 3, 4] },
  },
  {
    id: "add-3",
    title: "3.3. Вставить Рим в начало",
    desc: "Дан список base_cities. Вставьте 'Рим' в позицию 0 (в начало списка). Сохраните список в result.",
    vars: [{ name: "base_cities", type: "list[str]" }],
    setup: `base_cities = ${JSON.stringify(SECRET_DATA.base_cities)}`,
    starter: ``,
    hint: "Метод .insert(индекс, значение) вставляет элемент по индексу.",
    expected: { result: ["Рим", "Москва", "Париж"] },
  },
  {
    id: "add-4",
    title: "3.4. Расширить палитру",
    desc: "Дан список base_colors. Добавьте в конец сразу два цвета: 'синий' и 'жёлтый'. Сохраните список в result.",
    vars: [{ name: "base_colors", type: "list[str]" }],
    setup: `base_colors = ${JSON.stringify(SECRET_DATA.base_colors)}`,
    starter: ``,
    hint: "Метод .extend([...]) добавляет сразу несколько элементов.",
    expected: { result: ["красный", "зелёный", "синий", "жёлтый"] },
  },
  {
    id: "add-5",
    title: "3.5. Новый ученик",
    desc: "Дан список base_names. Добавьте в конец 'Миша'. Сохраните список в result.",
    vars: [{ name: "base_names", type: "list[str]" }],
    setup: `base_names = ${JSON.stringify(SECRET_DATA.base_names)}`,
    starter: ``,
    hint: "base_names.append(\"Миша\"); result = base_names.",
    expected: { result: ["Аня", "Петя", "Миша"] },
  },
  {
    id: "add-6",
    title: "3.6. Новая оценка",
    desc: "Дан список base_grades. Добавьте в конец оценку 5. Сохраните список в result.",
    vars: [{ name: "base_grades", type: "list[int]" }],
    setup: `base_grades = ${JSON.stringify(SECRET_DATA.base_grades)}`,
    starter: ``,
    hint: "base_grades.append(5).",
    expected: { result: [5, 4, 3, 5] },
  },
  {
    id: "add-7",
    title: "3.7. Новый питомец",
    desc: "Дан список base_pets. Добавьте в конец 'попугай'. Сохраните список в result.",
    vars: [{ name: "base_pets", type: "list[str]" }],
    setup: `base_pets = ${JSON.stringify(SECRET_DATA.base_pets)}`,
    starter: ``,
    hint: "base_pets.append(\"попугай\").",
    expected: { result: ["кошка", "собака", "попугай"] },
  },
  {
    id: "add-8",
    title: "3.8. Вставить среду",
    desc: "Дан список base_days. Вставьте 'среда' в позицию 1 (между понедельником и вторником). Сохраните список в result.",
    vars: [{ name: "base_days", type: "list[str]" }],
    setup: `base_days = ${JSON.stringify(SECRET_DATA.base_days)}`,
    starter: ``,
    hint: "base_days.insert(1, \"среда\").",
    expected: { result: ["понедельник", "среда", "вторник"] },
  },
  {
    id: "add-9",
    title: "3.9. Два новых вида спорта",
    desc: "Дан список base_sports. Добавьте в конец сразу 'бокс' и 'шахматы' (одним вызовом). Сохраните список в result.",
    vars: [{ name: "base_sports", type: "list[str]" }],
    setup: `base_sports = ${JSON.stringify(SECRET_DATA.base_sports)}`,
    starter: ``,
    hint: "base_sports.extend([\"бокс\", \"шахматы\"]).",
    expected: { result: ["футбол", "теннис", "бокс", "шахматы"] },
  },
  {
    id: "add-10",
    title: "3.10. Целая серия чисел",
    desc: "Дан список base_books. Добавьте в конец сразу две книги: 'Мастер и Маргарита' и 'Евгений Онегин'. Сохраните список в result.",
    vars: [{ name: "base_books", type: "list[str]" }],
    setup: `base_books = ${JSON.stringify(SECRET_DATA.base_books)}`,
    starter: ``,
    hint: "base_books.extend([...]).",
    expected: { result: ["Война и мир", "Мастер и Маргарита", "Евгений Онегин"] },
  },

  // ============================================================
  // ТЕМА 4. Удаление элементов из списка (10 задач)
  // ============================================================
  {
    id: "del-1",
    title: "4.1. Убрать вишню",
    desc: "Дан список del_fruits. Удалите из него 'вишня'. Сохраните получившийся список в result.",
    vars: [{ name: "del_fruits", type: "list[str]" }],
    setup: `del_fruits = ${JSON.stringify(SECRET_DATA.del_fruits)}`,
    starter: ``,
    hint: "Метод .remove(значение) удаляет первое вхождение элемента по значению.",
    expected: { result: ["яблоко", "банан", "груша", "слива"] },
  },
  {
    id: "del-2",
    title: "4.2. Убрать по индексу",
    desc: "Дан список del_numbers. Удалите элемент с индексом 2. Сохраните список в result.",
    vars: [{ name: "del_numbers", type: "list[int]" }],
    setup: `del_numbers = ${JSON.stringify(SECRET_DATA.del_numbers)}`,
    starter: ``,
    hint: "Оператор del удаляет по индексу: del del_numbers[2]. Или метод .pop(2).",
    expected: { result: [10, 20, 40, 50] },
  },
  {
    id: "del-3",
    title: "4.3. Убрать Токио",
    desc: "Дан список del_cities. Удалите из него 'Токио'. Сохраните список в result.",
    vars: [{ name: "del_cities", type: "list[str]" }],
    setup: `del_cities = ${JSON.stringify(SECRET_DATA.del_cities)}`,
    starter: ``,
    hint: "del_cities.remove(\"Токио\").",
    expected: { result: ["Москва", "Париж", "Каир"] },
  },
  {
    id: "del-4",
    title: "4.4. Удалить последний цвет",
    desc: "Дан список del_colors. Удалите последний элемент списка. Сохраните список в result.",
    vars: [{ name: "del_colors", type: "list[str]" }],
    setup: `del_colors = ${JSON.stringify(SECRET_DATA.del_colors)}`,
    starter: ``,
    hint: "Метод .pop() без аргумента удаляет последний элемент.",
    expected: { result: ["красный", "зелёный", "синий"] },
  },
  {
    id: "del-5",
    title: "4.5. Убрать Катю",
    desc: "Дан список del_names. Удалите из него 'Катя'. Сохраните список в result.",
    vars: [{ name: "del_names", type: "list[str]" }],
    setup: `del_names = ${JSON.stringify(SECRET_DATA.del_names)}`,
    starter: ``,
    hint: "del_names.remove(\"Катя\").",
    expected: { result: ["Аня", "Петя", "Миша", "Олег"] },
  },
  {
    id: "del-6",
    title: "4.6. Удалить двойку",
    desc: "Дан список del_grades. Удалите из него первую оценку 2. Сохраните список в result.",
    vars: [{ name: "del_grades", type: "list[int]" }],
    setup: `del_grades = ${JSON.stringify(SECRET_DATA.del_grades)}`,
    starter: ``,
    hint: "del_grades.remove(2) удалит первое вхождение числа 2.",
    expected: { result: [5, 4, 3, 5, 4] },
  },
  {
    id: "del-7",
    title: "4.7. Убрать первого питомца",
    desc: "Дан список del_pets. Удалите первый элемент списка. Сохраните список в result.",
    vars: [{ name: "del_pets", type: "list[str]" }],
    setup: `del_pets = ${JSON.stringify(SECRET_DATA.del_pets)}`,
    starter: ``,
    hint: "Можно так: del del_pets[0] или del_pets.pop(0).",
    expected: { result: ["собака", "хомяк", "рыбка"] },
  },
  {
    id: "del-8",
    title: "4.8. Убрать пятницу",
    desc: "Дан список del_days. Удалите из него 'пятница'. Сохраните список в result.",
    vars: [{ name: "del_days", type: "list[str]" }],
    setup: `del_days = ${JSON.stringify(SECRET_DATA.del_days)}`,
    starter: ``,
    hint: "del_days.remove(\"пятница\").",
    expected: { result: ["понедельник", "вторник", "среда", "четверг"] },
  },
  {
    id: "del-9",
    title: "4.9. Убрать два вида спорта",
    desc: "Дан список del_sports. Удалите из него 'теннис' и 'шахматы' (два отдельных вызова). Сохраните список в result.",
    vars: [{ name: "del_sports", type: "list[str]" }],
    setup: `del_sports = ${JSON.stringify(SECRET_DATA.del_sports)}`,
    starter: ``,
    hint: "del_sports.remove(\"теннис\") затем del_sports.remove(\"шахматы\").",
    expected: { result: ["футбол", "бокс"] },
  },
  {
    id: "del-10",
    title: "4.10. Убрать книгу-первоисточник",
    desc: "Дан список del_books. Удалите из него 'Война и мир' и последний элемент списка (два отдельных действия). Сохраните список в result.",
    vars: [{ name: "del_books", type: "list[str]" }],
    setup: `del_books = ${JSON.stringify(SECRET_DATA.del_books)}`,
    starter: ``,
    hint: "Сначала del_books.remove(\"Война и мир\"), затем del_books.pop() для удаления последнего.",
    expected: { result: ["Мастер и Маргарита", "Евгений Онегин"] },
  },
];
